import { StyleSheet } from 'react-native';
import { UI } from '@/constants/theme';

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        gap: 12,
    },
    backButton: {
        width: 40,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        color: '#000',
        fontSize: 18,
        fontWeight: '600',
    },
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        fontSize: 16,
        color: '#666',
    },
    tabsContainer: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        marginTop: 20,
        marginBottom: 20,
        backgroundColor: '#F3F4F6',
        borderRadius: 25,
        padding: 4,
        gap: 0,
    },
    tab: {
        flex: 1,
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 20,
        alignItems: 'center',
        backgroundColor: 'transparent',
    },
    activeTab: {
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    tabText: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '500',
    },
    activeTabText: {
        color: '#000',
        fontWeight: '600',
    },
    productsList: {
        flex: 1,
    },
    productsListContent: {
        paddingHorizontal: 20,
        paddingBottom: 20,
    },
    productCard: {
        flexDirection: 'row',
        backgroundColor: UI.colors.background,
        padding: 16,
        marginBottom: 12,
        borderRadius: UI.dimensions.borderRadius,
        borderWidth: UI.dimensions.borderWidth,
        borderColor: UI.colors.border,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    productImage: {
        width: 80,
        height: 80,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
    },
    productInfo: {
        flex: 1,
        marginLeft: 12,
        justifyContent: 'space-between',
    },
    productHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 4,
    },
    variantInfo: {
        fontSize: 12,
        color: '#64748B',
        fontStyle: 'italic',
        marginTop: 2,
        marginBottom: 4,
    },
    modalVariantText: {
        fontSize: 13,
        color: '#64748B',
        fontStyle: 'italic',
        marginTop: 4,
    },
    productTitle: {
        flex: 1,
        fontSize: 16,
        fontWeight: '600',
        color: '#000',
        lineHeight: 20,
        marginRight: 8,
    },
    productPrice: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#000',
        marginBottom: 2,
    },
    deliveryText: {
        fontSize: 12,
        color: '#666',
        marginBottom: 8,
    },
    statsRow: {
        flexDirection: 'row',
        gap: 16,
    },
    statItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    statText: {
        fontSize: 12,
        color: '#666',
    },
    orderCard: {
        flexDirection: 'row',
        backgroundColor: UI.colors.background,
        padding: 16,
        marginBottom: 12,
        borderRadius: UI.dimensions.borderRadius,
        borderWidth: UI.dimensions.borderWidth,
        borderColor: UI.colors.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    orderImage: {
        width: 72,
        height: 72,
        borderRadius: 10,
        backgroundColor: '#F3F4F6',
    },
    orderInfo: {
        flex: 1,
        marginLeft: 14,
    },
    orderHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 6,
    },
    orderTitle: {
        flex: 1,
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        marginRight: 12,
    },
    statusBadge: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    statusBadgeText: {
        fontSize: 11,
        fontWeight: '600',
    },
    orderPrice: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1D4ED8',
        marginBottom: 6,
    },
    orderMeta: {
        fontSize: 13,
        color: '#4B5563',
        marginBottom: 2,
    },
    orderMetaSmall: {
        fontSize: 12,
        color: '#6B7280',
        marginBottom: 2,
    },
    orderMetaLink: {
        fontSize: 12,
        color: '#2563EB',
        fontWeight: '600',
        marginTop: 4,
        textDecorationLine: 'underline',
    },
    orderActionButton: {
        marginTop: 12,
        backgroundColor: '#4F46E5',
        borderRadius: UI.dimensions.borderRadius,
        height: UI.dimensions.buttonHeight,
        justifyContent: 'center',
        alignItems: 'center',
    },
    orderActionText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
    },
    orderHint: {
        marginTop: 10,
        fontSize: 12,
        color: '#6B7280',
    },
    orderLink: {
        marginTop: 10,
    },
    orderLinkText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#4F46E5',
        textDecorationLine: 'underline',
    },
    optionsButton: {
        padding: 8,
        alignSelf: 'flex-start',
    },
    floatingAddButton: {
        position: 'absolute',
        marginHorizontal: 20,
        bottom: 50,
        transform: [{ translateX: 0 }],
        width: '90%',
        height: UI.dimensions.buttonHeight,
        borderRadius: UI.dimensions.borderRadius,
        backgroundColor: UI.colors.primary,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    floatingButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    bottomSpacing: {
        height: 20,
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    errorText: {
        fontSize: 16,
        color: '#EF4444',
        textAlign: 'center',
        marginBottom: 16,
    },
    retryButton: {
        backgroundColor: UI.colors.primary,
        paddingHorizontal: 24,
        height: UI.dimensions.buttonHeight,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: UI.dimensions.borderRadius,
    },
    retryButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    modalCard: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 24,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
        textAlign: 'center',
        marginBottom: 8,
    },
    modalDescription: {
        fontSize: 14,
        color: '#6B7280',
        marginBottom: 16,
    },
    modalSection: {
        marginBottom: 16,
    },
    modalSectionTitle: {
        fontSize: 13,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 4,
        textTransform: 'uppercase',
    },
    modalInfoText: {
        fontSize: 13,
        color: '#374151',
        marginBottom: 2,
    },
    modalLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 6,
    },
    modalInput: {
        borderWidth: UI.dimensions.borderWidth,
        borderColor: UI.colors.border,
        borderRadius: UI.dimensions.borderRadius,
        paddingHorizontal: 16,
        height: UI.dimensions.inputHeight,
        fontSize: 14,
        color: '#111827',
        backgroundColor: UI.colors.backgroundLight,
    },
    modalInputMultiline: {
        height: 80,
        textAlignVertical: 'top',
    },
    modalError: {
        color: '#B91C1C',
        fontSize: 13,
        marginBottom: 12,
    },
    modalHint: {
        fontSize: 12,
        color: '#6B7280',
        marginBottom: 12,
    },
    modalActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        gap: 12,
    },
    modalButton: {
        flex: 1,
        backgroundColor: '#4F46E5',
        paddingHorizontal: 18,
        height: UI.dimensions.buttonHeight,
        borderRadius: UI.dimensions.borderRadius,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalButtonText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 14,
    },
    modalButtonOutline: {
        backgroundColor: '#EEF2FF',
    },
    modalButtonOutlineText: {
        color: '#312E81',
    },
    modalButtonDisabled: {
        backgroundColor: '#CBD5F5',
    },
    modalButtonDisabledText: {
        color: '#FFFFFF',
        opacity: 0.6,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 60,
        paddingHorizontal: 20,
    },
    emptyText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 8,
    },
    emptySubtext: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        lineHeight: 20,
    },
});

